### ISSUE TITLE
更新某系列，title 重複會導致 500 錯誤。

### ISSUE THREAD

**Issue by passerbyid** [GlobalMDS/API#2]
#### body
```json
{"locales":[{"lang":"zh-tw","title":"測試系列"}]}
```
#### error
```
QueryException in Connection.php line 662:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '測試系列' for key 'series_i18n_title_unique' (SQL: update `series_i18n` set `title` = 測試系列, `updated_at` = 2016-10-18T23:51:29+0800 where `id` = 33)
```

**Comment by zxp86021** [comment]
這是資料庫設計問題，所以是 i18n title 都不設定 unique 嗎？

**Comment by passerbyid** [comment]
i18n title 是否得是唯一，該是設計問題，因為不是唯一不會影響系統，而是會影響使用者。

若是檢查，是對管理產品更友善，所以目前除了型號以外，應該都是要檢查是否為重複。
但就算如此，也不該噴系統錯誤，而應該要回應錯誤訊息。

**Comment by zxp86021** [comment]
上傳新版本，目前會檢查除本身外 title 是否有重複
https://github.com/GlobalMDS/API/commit/3a842afcec257f6d9a0056ecac2e5f831873c046

**Comment by passerbyid** [comment]
看起來沒什麼問題，只有型號的 title 可以重複。
但「除本身外」是什麼意思？
