### ISSUE TITLE
更新產品資訊不完全成功。

### ISSUE THREAD

**Issue by passerbyid** [GlobalMDS/API#3]
PATCH Product 時，`description` 與 `detail` 欄位不會更新。
## Request Sample
PATCH `https://api.gmds.im.ncnu.edu.tw/categories/8/series/33/products/18 `
### Body
```json
{
	"locales": [
		{
			"lang": "zh-tw",
			"title": "測試產品",
			"description": "測試敘述",
			"detail": "測試詳細"
		},
		{
			"lang": "de",
			"title": "Test Product",
			"description": "",
			"detail": ""
		}
	]
}
```

**Comment by zxp86021** [comment]
應該已在 https://github.com/GlobalMDS/API/commit/2b8131ccdf9d5239b8c659906b4ffdce31d4b54d commit 中修復
